"""Snippets exercising safe_eval edge cases; the oracle decides what is right."""

SNIPPETS = {
    "empty": "",
    "assign": "x = 1",
    "dunder_string_literal": "name = '__TEST__'\nmsg = \"Status: __PENDING__\"",
    "dunder_attr": "x = record.__class__",
    "dunder_name": "x = __name__",
    "dunder_in_middle": "temp__test = 1",
    "unsafe_attr_mro": "x = str.mro()",
    "unsafe_attr_f_globals": "def f():\n    pass\nx = f.f_globals",
    "gi_frame": "g = (i for i in range(3))\nx = g.gi_frame",
    "import": "import os",
    "from_import": "from datetime import date",
    "store_attr": "record.name = 'x'",
    "store_attr_in_loop": "for r in records:\n    r.name = 'x'",
    "delete_attr": "del record.name",
    "delete_subscr": "d = {'a': 1}\ndel d['a']",
    "delete_name": "x = 1\ndel x",
    "global_stmt": "def f():\n    global y\n    y = 1",
    "assert": "assert records",
    "with": "with env.cr.savepoint():\n    pass",
    "class": "class A:\n    pass",
    "star_unpack": "a, *b = [1, 2, 3]",
    "star_tuple": "t = (*[1, 2], 3)",
    "star_list": "t = [*[1, 2], 3]",
    "star_call": "f = lambda *a: a\nx = f(*[1, 2])",
    "dict_merge": "d = {**{'a': 1}, 'b': 2}",
    "lambda": "f = lambda x: x + 1\ny = f(1)",
    "def": "def f(x, y=2):\n    return x + y\nz = f(1)",
    "closure": "def outer():\n    x = 1\n    def inner():\n        return x\n    return inner()",
    "comprehension_top": "xs = [r.id for r in records if r]",
    "comprehension_in_func_uses_local": "def f(n):\n    return [i * n for i in range(3)]\nx = f(2)",
    "generator": "g = sum(i for i in range(10))",
    "dict_comp": "d = {k: v for k, v in [(1, 2)]}",
    "set_comp": "s = {i for i in range(3)}",
    "yield": "def g():\n    yield 1\nx = list(g())",
    "yield_from": "def g():\n    yield from [1, 2]",
    "try_except": "try:\n    x = 1\nexcept Exception as e:\n    x = 2",
    "try_finally": "try:\n    x = 1\nfinally:\n    y = 2",
    "try_except_else": "try:\n    x = 1\nexcept Exception:\n    pass\nelse:\n    y = 2",
    "raise_usererror": "raise UserError('x')",
    "while": "i = 0\nwhile i < 3:\n    i += 1",
    "break_continue": "for i in range(5):\n    if i == 1:\n        continue\n    if i == 3:\n        break",
    "walrus": "if (n := len([1, 2])) > 1:\n    x = n",
    "fstring": "x = f'{1 + 1} items'",
    "fstring_spec": "x = f'{3.14159:.2f} {\"a\"!r}'",
    "percent_format": "x = 'a %s' % 1",
    "slice": "x = [1, 2, 3][1:]",
    "slice_assign": "x = [1, 2, 3]\nx[0:1] = [9]",
    "subscript_assign": "d = {}\nd['a'] = 1",
    "augassign_subscr": "d = {'a': 1}\nd['a'] += 1",
    "augassign_attr": "record.x += 1",
    "chained_compare": "x = 1 < 2 < 3",
    "is_none": "x = None\ny = x is None",
    "in_op": "y = 1 in [1, 2]",
    "ternary": "x = 1 if records else 2",
    "boolean_ops": "x = records and records[0] or False",
    "matmul": "x = 1 @ 2",
    "match": "x = 1\nmatch x:\n    case 1:\n        y = 1",
    "async_def": "async def f():\n    pass",
    "annotation": "x: int = 1",
    "annotation_in_func": "def f(a: int) -> int:\n    return a",
    "unicode": "x = 'žluťoučký kůň'",
    "nested_func_default": "def f(a, b=[1]):\n    return a",
    "kwargs_dunder": "def f(**kw):\n    return kw\nx = f(**{'__a': 1})",
    "leading_blank_lines": "\n\n\nx = 1\n",
    "indented_first_line": "    x = 1\n    y = 2",
    "indented_block": "    x = 1\ny = 2",
    "syntax_error": "x = (1,",
    "tab_indent": "if records:\n\tx = 1",
    "odoo_action_return": "action = {'type': 'ir.actions.client', 'tag': 'display_notification', 'params': {'message': 'ok'}}",
    "env_calls": "partners = env['res.partner'].sudo().search([('is_company', '=', True)], limit=5)\nnames = partners.mapped('name')",
    "command": "records.write({'tag_ids': [Command.link(1)]})",
    "log": "log('hello', level='info')",
    "datetime_usage": "d = datetime.datetime.now() + dateutil.relativedelta.relativedelta(days=1)\nt = time.time()",
    "print_call": "print('x')",
    "type_call": "t = type(record)",
    "getattr_call": "x = getattr(record, 'name')",
    "global_builtin_exception": "raise Exception('x')",
    "reduce": "x = reduce(lambda a, b: a + b, [1, 2, 3])",
    "docstring_first": "\"\"\"Recompute totals.\"\"\"\nx = 1",
    "string_not_first": "x = 1\n'just a string'",
    "walrus_in_comprehension_top": "ys = [y for x in [1, 2] if (y := x)]",
    "walrus_in_comprehension_in_def": "def f():\n    return [y for x in [1, 2] if (y := x)]",
    "genexp_in_def_uses_local": "def f(n):\n    return sum(i * n for i in range(3))",
    "lambda_in_def_uses_local": "def f(n):\n    return list(map(lambda i: i * n, range(3)))",
    "lambda_uses_toplevel": "t = 3\nxs = list(filter(lambda r: r > t, [1, 5]))",
    "match_sequence": "match [1, 2]:\n    case [a, b]:\n        x = a",
    "match_mapping": "match {'a': 1}:\n    case {'a': v}:\n        x = v",
    "match_class": "match 1:\n    case int():\n        x = 1",
    "nonlocal": "def f():\n    x = 1\n    def g():\n        nonlocal x\n        x = 2\n    g()",
    "mro_variable": "mro = 1",
    "raise_bare": "try:\n    raise UserError('x')\nexcept UserError:\n    raise",
    "yield_toplevel": "yield 1",
    "return_toplevel": "return 1",
    "subscript_field_set": "record['name'] = 'x'",
    "except_keyerror": "try:\n    x = {}['a']\nexcept KeyError:\n    x = None",
    "long_code": "\n".join(f"x{i} = {i}" for i in range(400)),
    "large_jump": "if records:\n" + "\n".join(f"    x{i} = {i}" for i in range(3000)),
}
