"""Per-Odoo-version data (generated by tools/sync_odoo.py) resolved for the running interpreter."""
from __future__ import annotations

import functools
import json
import opcode
import sys
from dataclasses import dataclass
from importlib import resources

CALLERS = ("server_action", "cron", "automation")


def available_versions() -> list[str]:
    names = [p.name for p in resources.files("sevlint.data").iterdir()
             if p.name.startswith("odoo-") and p.name.endswith(".json")]
    return sorted((n[len("odoo-"):-len(".json")] for n in names), key=version_key)


def version_key(version: str) -> tuple[int, int]:
    """(major, minor): '19.0' -> (19, 0), 'saas-19.2' -> (19, 2)."""
    major, _, minor = normalize_version(version).removeprefix("saas-").partition(".")
    try:
        return int(major), int(minor or 0)
    except ValueError:
        return (0, 0)


def normalize_version(value: str | int | float) -> str:
    """'19', '19.0', '19.0.1.0.0' -> '19.0'; 'saas-19.2', 'saas~19.2' (Odoo Online), '19.2' -> 'saas-19.2'."""
    text = str(value).strip().lower().replace("saas~", "saas-")
    saas = text.startswith("saas-")
    text = text.removeprefix("saas-")
    if text.isdigit():
        text += ".0"
    text = ".".join(text.split(".")[:2])
    major, _, minor = text.partition(".")
    if saas or (minor.isdigit() and int(minor) > 0):
        return f"saas-{major}.{minor or '0'}"
    return text


@dataclass(frozen=True)
class Profile:
    odoo_version: str
    python_min: tuple[int, int]
    python_max: tuple[int, int] | None  # None: the branch declares no maximum
    safe_opcodes: frozenset[int]
    unsafe_attributes: frozenset[str]
    builtins: frozenset[str]
    context_core: frozenset[str]
    context_addons: dict[str, tuple[str, ...]]
    wrapped_modules: dict[str, dict[str, tuple[str, ...] | None]]
    source_commit: str
    sandbox_policy: str | None = None  # 19.3+: default --unsafe-policy of the runtime sandbox

    @property
    def python_supported(self) -> bool:
        running = sys.version_info[:2]
        return self.python_min <= running and (self.python_max is None or running <= self.python_max)

    @property
    def python_range(self) -> str:
        lo = ".".join(map(str, self.python_min))
        return f"{lo}-{'.'.join(map(str, self.python_max))}" if self.python_max else f"{lo}+"


def _to_opcodes(names: list[str]) -> set[int]:
    # Same semantics as odoo.tools.safe_eval.to_opcodes: unknown names are skipped.
    return {opcode.opmap[n] for n in names if n in opcode.opmap}


@functools.lru_cache(maxsize=None)
def load(version: str) -> Profile:
    version = normalize_version(version)
    try:
        raw = resources.files("sevlint.data").joinpath(f"odoo-{version}.json").read_text()
    except FileNotFoundError:
        raise ValueError(f"unsupported Odoo version {version!r}; known: {', '.join(available_versions())}") from None
    data = json.loads(raw)
    ops = data["opcodes"]
    # Mirrors safe_eval.py: every set is built from opcode numbers and minus _BLACKLIST.
    blacklist = _to_opcodes(ops["blacklist"])
    const = _to_opcodes(ops["const"]) - blacklist
    expr = (const | _to_opcodes(ops["expr_extra"])) - blacklist
    safe = (expr | _to_opcodes(ops["safe_extra"])) - blacklist
    return Profile(
        odoo_version=version,
        python_min=tuple(data["python"]["min"]),
        python_max=tuple(data["python"]["max"]) if data["python"]["max"] else None,
        safe_opcodes=frozenset(safe),
        unsafe_attributes=frozenset(data["unsafe_attributes"]),
        builtins=frozenset(data["builtins"]),
        context_core=frozenset(data["context"]["core"]),
        context_addons={k: tuple(v) for k, v in data["context"]["addons"].items()},
        wrapped_modules={
            mod: {attr: (tuple(sub) if sub is not None else None) for attr, sub in attrs.items()}
            for mod, attrs in data["wrapped_modules"].items()
        },
        source_commit=data["source"]["commit"],
        sandbox_policy=(data.get("sandbox") or {}).get("unsafe_policy_default"),
    )
