"""Per-Odoo-version data (generated by tools/sync_odoo.py) resolved for the running interpreter."""
from __future__ import annotations

import functools
import json
import opcode
import sys
from dataclasses import dataclass
from importlib import resources

CALLERS = ("server_action", "cron", "automation")


def available_versions() -> list[str]:
    names = [p.name for p in resources.files("sevlint.data").iterdir() if p.name.startswith("odoo-")]
    return sorted((n[len("odoo-"):-len(".json")] for n in names), key=lambda v: float(v))


def normalize_version(value: str | int | float) -> str:
    text = str(value).strip()
    if text.isdigit():
        text += ".0"
    parts = text.split(".")
    if len(parts) > 2:  # manifest style 19.0.1.0.0
        text = ".".join(parts[:2])
    return text


@dataclass(frozen=True)
class Profile:
    odoo_version: str
    python_min: tuple[int, int]
    python_max: tuple[int, int]
    safe_opcodes: frozenset[int]
    unsafe_attributes: frozenset[str]
    builtins: frozenset[str]
    context_core: frozenset[str]
    context_addons: dict[str, tuple[str, ...]]
    wrapped_modules: dict[str, dict[str, tuple[str, ...] | None]]
    source_commit: str

    @property
    def python_supported(self) -> bool:
        return self.python_min <= sys.version_info[:2] <= self.python_max


def _to_opcodes(names: list[str]) -> set[int]:
    # Same semantics as odoo.tools.safe_eval.to_opcodes: unknown names are skipped.
    return {opcode.opmap[n] for n in names if n in opcode.opmap}


@functools.lru_cache(maxsize=None)
def load(version: str) -> Profile:
    version = normalize_version(version)
    try:
        raw = resources.files("sevlint.data").joinpath(f"odoo-{version}.json").read_text()
    except FileNotFoundError:
        raise ValueError(f"unsupported Odoo version {version!r}; known: {', '.join(available_versions())}") from None
    data = json.loads(raw)
    ops = data["opcodes"]
    # Mirrors safe_eval.py: every set is built from opcode numbers and minus _BLACKLIST.
    blacklist = _to_opcodes(ops["blacklist"])
    const = _to_opcodes(ops["const"]) - blacklist
    expr = (const | _to_opcodes(ops["expr_extra"])) - blacklist
    safe = (expr | _to_opcodes(ops["safe_extra"])) - blacklist
    return Profile(
        odoo_version=version,
        python_min=tuple(data["python"]["min"]),
        python_max=tuple(data["python"]["max"]),
        safe_opcodes=frozenset(safe),
        unsafe_attributes=frozenset(data["unsafe_attributes"]),
        builtins=frozenset(data["builtins"]),
        context_core=frozenset(data["context"]["core"]),
        context_addons={k: tuple(v) for k, v in data["context"]["addons"].items()},
        wrapped_modules={
            mod: {attr: (tuple(sub) if sub is not None else None) for attr, sub in attrs.items()}
            for mod, attrs in data["wrapped_modules"].items()
        },
        source_commit=data["source"]["commit"],
    )
